name: CI
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install toml
        run: |
          pip install toml
      - name: Show Dir
        run: |
          ls -R
      - name: Show Dir
        run: |
          pwd
      - name: Check pypi versions
        id: versioncheck
        run: python .github/workflows/version.py
        
      
      - name: check output
        run: |
            echo "Version: ${{ steps.versioncheck.outputs.version }}"
